//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flairdocs_Workflow_Designer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public int Id { get; set; }
        public int ReviewerId { get; set; }
        public string Creation_Date { get; set; }
    
        public virtual Reviewer Reviewer { get; set; }
    }
}
