//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flairdocs_Workflow_Designer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transition
    {
        public System.Guid Id { get; set; }
        public string Conditions { get; set; }
        public System.Guid WorkflowId { get; set; }
    
        public virtual Workflow Workflow { get; set; }
    }
}
